### ISSUE TITLE
Unresolvable parameter in annotation

### ISSUE THREAD

**Issue by svorkoetter** [queraltab/Greenhouses-Library#13]
When flattening the GlobalSystem_2 example, MapleSim issues a warning that the name PumpType in an annotation in Greenhouses.Flows.FluidFlow.Pump_Mdot cannot be resolved. Searching through the entire source code, the only place this name appears is Flows/FluidFlow/Pump_Mdot.mo, once in the offending annotation,
```
parameter Real eta_is=1 "Overall Isentropic efficiency of the pump" annotation (Dialog(enable= (PumpType == "User Defined")));
```
and once in the Documentation annotation:
```
<li>PumpType: select between different performance curves for isentropic and volumetric efficiencies.</li>
```
The parameter isn't actually defined anywhere.

**Comment by queraltab** [comment]
The "enable" annotation was related to an obsolete parameter because it was used in a previous version of the model. The actual model does no longer make use of this parameter. The annotation has been removed so the issue is solved. Thanks for your collaboration!
