### ISSUE TITLE
Library icon depends on ThermoCycle library

### ISSUE THREAD

**Issue by beutlich** [queraltab/Greenhouses-Library#3]
The library icon depends on the ThermoCycle library.

https://github.com/queraltab/Greenhouses-Library/blob/1b3c8b04646bddebe8f5f4b460e6f51f8e4ff5b2/Greenhouses/package.mo#L36

I propose to remove that dependency by copying the ThermoCycleLibrary.png (if allowed to do so).

**Comment by queraltab** [comment]
Thanks. The dependency is now removed.
