### ISSUE TITLE
Missing package icons

### ISSUE THREAD

**Issue by beutlich** [queraltab/Greenhouses-Library#9]
The following packages miss an icon

Greenhouses.Components
Greenhouses.Flows
Greenhouses.Flows.FluidFlow.Reservoirs
Greenhouses.ControlSystems
Greenhouses.ControlSystems.Climate.Utilities
Greenhouses.ControlSystems.HVAC
Greenhouses.Functions.Enumerations
Greenhouses.Functions.TestRig
Greenhouses.Icons
Greenhouses.Icons.Water

**Comment by queraltab** [comment]
Not anymore :) Thanks
